### ISSUE TITLE
`query` is undefined when passing a function callback for "data"

### ISSUE THREAD

**Issue by tleunen** [effektif/react-mentions#102]
Trying to use a custom function (called provider) for the data of a mention, but the query is always undefined.

It tries to access `match[2]` but it doesn't exist so it results in a undefined value passed to the function :s
![screen shot 2016-05-25 at 4 26 18 pm](https://cloud.githubusercontent.com/assets/1972567/15555145/7171956a-2295-11e6-980b-ff1723f8c6e4.png)

**Comment by tleunen** [comment]
Looks like the regex requires to be in a specific format. See https://github.com/effektif/react-mentions/blob/master/src/MentionsInput.js#L25

**Comment by jfschwarz** [comment]
Correct, the current regex must be in a specific format. Issue #21 is related to this, and there has been some implementation started on branch 'custom-regex'. However, that branch is stale since quite some time ago as we, and apparently nobody else, seemed to have regex customizability as a requirement. If you would like to pick up working on this, I'd be happy to help out ;)
