### ISSUE TITLE
Cursor is not at the right location when using `displayTransform`

### ISSUE THREAD

**Issue by tleunen** [effektif/react-mentions#103]
The title says it all, but when I customize the display with `displayTransform`, the cursor doesn't seem to be at the right location, especially if the new display has more characters than the default display.

**Comment by tleunen** [comment]
It might also be related to the custom `markup` I was using... `markup="{{__id__}}"`.

With this markup, the displayTransform gets called with the id instead of the display data from the suggestion. Seems to work fine with the default markup.

**Comment by jfschwarz** [comment]
> With this markup, the displayTransform gets called with the id instead of the display data from the suggestion.

This is expected behavior. The mentions markup only dispatches queries / lookups using the `data` prop for calculating suggestions, it doesn't do it for just rendering existing mention items. So all values that are passed to the `displayTransform` prop must be part of the markup.

I can't really tell how the bug you described might be related to this. Check out the example component using a display transform, which also has more characters than the default display: https://github.com/effektif/react-mentions/blob/master/gh-pages/views/examples/AdvancedView.js
