### ISSUE TITLE
How to add a link for each selected suggestion

### ISSUE THREAD

**Issue by warjohn123** [effektif/react-mentions#129]
I used this code to generate my textarea with mentions. My question is how do I insert a link for selected suggestions?

<MentionsInput
                    type="text"
                    value={this.state.value}
                    onBlur={this.onBlur}
                    onChange={this.onChange}
                    placeholder={this.props.placeholder}
                    id={this.props.id}
                    name={this.props.name}
                    className={this.props.className}>

                    <Mention trigger="@"
                             data={this.state.items}
                             renderSuggestion={this.renderSuggestion}
                             onAdd={this.handleAdd}
                             style={{ backgroundColor: '#5bc0de' }}/>

</MentionsInput>

**Comment by jfschwarz** [comment]
I'm not sure if I fully understand what you're trying to do... What's your use case for inserting links for mentions?

react-mentions is only capable of highlighting specific text ranges in a textarea. It does that by rendering a div behind the textarea that contains the highlighting background elements. Due to that div lying **behind** the textarea it is not possible for the highlighting elements to receive mouse events. Maybe a rich-text editor such as Draft.js might be more suitable for your use case?

**Comment by warjohn123** [comment]
Thanks for the response but I already solved this problem. I simply created a customized function for displayTransform.

**Comment by jfschwarz** [comment]
Ok, great!

**Comment by meuschke** [comment]
@warjohn123 can you post an example how you did the link integration in displayTransform ?
