### ISSUE TITLE
Text Area auto size does not work properly when the line height is a bit different (27px)

### ISSUE THREAD

**Issue by killerdejavu** [effektif/react-mentions#145]
We use a different line height for the text area, and it messes up the text area on every new line. It actually pushes the previous content further top and scroll bar comes up. I think it might be because the space added on new line is different from the line height of the text ?

**Comment by jfschwarz** [comment]
Make sure to adjust the styling of the highlighter element accordingly. The way the mentions highlighting is by mirroring the input text to a div positioned exactly behind the textarea. While the color of the mirrored text is transparent, the mentioned words are wrapped in spans with a background color.

Hope this helps. Otherwise, please create a jsfiddle demonstrating your problem so we can take a look.

**Comment by killerdejavu** [comment]
@jfschwarz Thanks for the update! We solved the issue by the same approach you suggested. Closing this issue.
