### ISSUE TITLE
use as HOC on existing element

### ISSUE THREAD

**Issue by smeijer** [effektif/react-mentions#153]
Is it possible to use this library as a HOC on an already existing element? If not; it would be nice to have functionality like that.

Situation; I currently have a `content-editable` `div`, with some logic of my own. It would be awesome if I could simply wrap this mentions library, and have a way to inject the mentions into my own control / element.

Something like:

```jsx
import React from 'react';
import { withMentions } from 'react-mentions'

import { UserSuggestions, TagSuggestions, EmojiSuggestions } from './suggestions';

const MyInput = ({}) => (
  <div contentEditable />
);

export default compose(
  withMentions('@', UserSuggestions),      // trigger, component
  withMentions('#', TagSuggestions, tags), // trigger, component, data
  withMentions(':', EmojiSuggestions),     // trigger, component
)(MyInput);
```

**Comment by jfschwarz** [comment]
While the API you drafted looks nice, it does't seem feasible to implement this with react-mentions. First, react-mentions doesn't use `content-editable` but renders a regular `textarea` with highlighting `div`s in the background positioned to lie behind mentioned items. Second, due to the complexity of managing selection state (i.e. cursor position) I'm afraid that things will go bananas if react-mentions does not have exclusive control over the textarea's value.
