### ISSUE TITLE
Ability to pass className to the generated input/textarea

### ISSUE THREAD

**Issue by lorinkoz** [effektif/react-mentions#165]
Not sure how to render the input/textarea to display nicely with Bootstrap, as it requires some classes applied directly to the generated input/textarea. I couldn't do it as of now, any workaround?

**Comment by frontendphil** [comment]
Hey there! Simply add a `className` prop to the `Mentions` component. We'll generate custom `className` attributes for each sub-component for you. Simply inspect the DOM and look at the output.

**Comment by lorinkoz** [comment]
I tried passing `className="form-control"` to give the bootstrap look, and it's displayed awkwardly. I inspected the code and the class is applied to one of the wrapper divs, not the actual input/textarea element. Am I doing anything wrong?

**Comment by jfschwarz** [comment]
This is indeed a shortcoming of the current mechanism: class names of nested elements can not be directly set, but are derived automatically from the `className` prop passed to the `Mention` element.

I'm currently working on a mechanism, that allows to pass a `classNames` mapping prop which you could use to set Bootstrap class names directly on the `input` element. I expect it to be available later this week.

**Comment by jfschwarz** [comment]
@lorinkoz I just created PR #166. If you like you can already checkout that branch to try out whether you can achieve the Bootstrap styling.

Basically, it should work as follows:

```
<MentionsInput
  classNames={{
    mentions__input: 'form-control'
  }}
>
  ...
</MentionsInput>
```

You need to make sure though, that the `highlighter` element is receiving matching font sizes, paddings, etc. so that the mentions backgrounds are actually positioned correctly. It might be worth a trial setting the `'form-control'` class name on the `mentions__control` element instead, or on both `mentions__input` and `mentions__highlighter`. You'll have to experiment a bit. If you find a solution, please post here as it might be useful for others, too. Thank you! 👍

**Comment by lorinkoz** [comment]
@jfschwarz Will do soon, thanks!

**Comment by jfschwarz** [comment]
css modules support has been release with v1.2.0. hope this is helpful also for your use case.

**Comment by doublejosh** [comment]
Note that this breaks once you get down to `mentions__suggestions__item--focused`
