### ISSUE TITLE
Suggestion Overlay isn't capturing focus?

### ISSUE THREAD

**Issue by MrNice** [effektif/react-mentions#173]
In the examples, when the mention functionality is triggered and the overlay is displayed, you can use the arrow keys to select a suggestion and then enter to commit.

In our app, this functionality doesn't work - the keystrokes stay in the text area & the overlay never receives focus.

We tried wrapping our parent component with Radium as you do in examples, to no avail.

Do you have any hints for diagnosing this kind of issue? I can't provide code snippets, but I eventually had my renderSuggestion function directly pass through the `highlighted` parameter and that still wouldn't catch the focus.

Also, if this component requires radium to function "correctly", could that be somewhere in the docs?

**Comment by frontendphil** [comment]
Hey @MrNice what exactly are you trying to accomplish? It is correct behavior that the focus stays in the `textarea`. When we know that the suggestions are shown, we simply trigger extra actions in order to make it possible to select values in the list. This is done by intercepting the events for `arrowUp` and `arrowDown`, canceling them for the current `textarea` and moving the highlighter position instead. 

FYI `radium` has nothing to do with that. We also do not require `radium`, we just use it in our examples. Since this package uses `substyle` it is compatible with multiple styling approaches.

**Comment by MrNice** [comment]
Problem was [react-shortcuts](https://github.com/avocode/react-shortcuts) preventing all descendant event handlers on keystrokes from firing. The solution was to set `stopPropagation` to false, and remove collisions between the local Shortcuts handler and the global Shortcuts handler.
