### ISSUE TITLE
Mention that is fully typed, and not selected via the dropdown, doesn't create a mention 

### ISSUE THREAD

**Issue by omerts** [effektif/react-mentions#177]
Hey,

I think this is more of an enhancement request. 
When I type out my mention, and don't select it via the dropdown, I can see the mention being highlighted as I go, but once I finish typing it, it is not recognized as a mention. The onChange function doesn't add it to the mentions array, nor does it get the special formatting of an added mention.

Omer

**Comment by frontendphil** [comment]
Hey @omerts thanks for your feedback. This kind of behavior is intentional. We're trying to do the least amount of magic. Adding a mention even though the user didn't especially state he/she wants to perform this action falls into this category. We cannot know whether typing out something meant that it should be added or that the user simply didn't want to insert the mention it this point in time.

**Comment by jsheffers** [comment]
In our case, we are displaying the trigger with the display text, so this would be relevant for us.  There will never be a case when someone types @JohnnyAppleseedSmith that shouldn't be automatically transformed into a mention.  I understand if this is too difficult of a change to implement but I'm curious to see if this is still the project's stance on this front?

For example
`shane` would not show a mention, but `@shane` would.
