### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by questymark** [effektif/react-mentions#197]
Hello, I'm getting this error whenever I try to render my app.

React 15.6.2,
Webpack 1.13.1

**Comment by frontendphil** [comment]
Do you set a non `null`,  non `undefined` `value` prop?

**Comment by t1mmen** [comment]
I'm running into this issue too, after upgrading from 0.6 to 1.2.0. It _only_ occurs when I build for production. 

Here are some relevant screenshots:
![screenshot 2017-09-29 13 50 59](https://user-images.githubusercontent.com/192263/31035708-d4a6da62-a51d-11e7-92d2-4c5fececb4b5.png)

console.log output
<img width="539" alt="screenshot 2017-09-29 13 47 44" src="https://user-images.githubusercontent.com/192263/31035719-dbafbd9c-a51d-11e7-91f6-3723cccb6b0c.png">


Webpack 1.13.2, React 15.4.2.

**Comment by t1mmen** [comment]
It looks like substyle and/or lodash could be playing a role here. I attempted to upgrade each to their latest versions, `npm run transpile` and copy the conents of `lib` to my local `node_modules/react-mentions/lib`, but no dice:

![screen shot 2017-10-02 at 11 28 12 am](https://user-images.githubusercontent.com/192263/31093988-5d8bd03e-a768-11e7-8393-1fe6c3558f93.png)

**Comment by saidymadi** [comment]
I believe I worked around this issue as follow 
![image](https://user-images.githubusercontent.com/15877259/31094741-328d2b64-a784-11e7-8e87-d0c5397bec74.png)

**Comment by questymark** [comment]
I solved this problem.
I've delete lodash-webpack-plugin from my project.

**Comment by t1mmen** [comment]
Seems like `lodash-webpack-plugin` could be the cause of this issue -- we're using it for production builds as well.

**Comment by jfschwarz** [comment]
While I didn't try reproducing it yet, I suspect that your markup pattern might be problematic because the `__type__` and `__display__` placeholders are not separated by any markup characters. Thus, react-mentions won't be able to tell where the `type` section ends and where the `display` section starts. Note that both placeholders are optional, so a markup value of `'[`__display__`](__id__)'` would probably work for you.

**Comment by delgermurun** [comment]
@jfschwarz Thank you for reply.

Removing `__type__` from markup broke mentioning. I guess it is because of we have a multiple types of mentions.

Separating `__type__` and `__display__` (such as `__type__|__display__`) by character fixes error. But we do need to do by such way (`__type____display__`) because of UI reason. It works fine until above problem comes up.

**Comment by isakulaksiz** [comment]
I've same error.Could you help me please?
How did you solve it ?

**Comment by jayacados** [comment]
I'm also running into this issue as well in production. I've tried this fix and can't seem to resolve it. Any solutions on this?

**Comment by manglaaseem28** [comment]
Pretty weird in one component .length runs perfectly fine, but in a different component, this was showing an error.
TypeError: Cannot read property 'length' of undefined
Please Help

**Comment by anogray** [comment]
I had the same issue but

![image](https://user-images.githubusercontent.com/57917151/121354860-edd83880-c94c-11eb-9ee4-da88c035f51b.png)

 it was mine mistake as I pushed frontend but didn't push backend changes.

**Comment by kinjaldave-tech** [comment]
> I had the same issue but
> 
> ![image](https://user-images.githubusercontent.com/57917151/121354860-edd83880-c94c-11eb-9ee4-da88c035f51b.png)
> 
> it was mine mistake as I pushed frontend but didn't push backend changes.

hey i'm getting same error how to solve it?
