### ISSUE TITLE
Optional Styling(We dont need default styling in open libs)

### ISSUE THREAD

**Issue by almeida-samuel** [effektif/react-mentions#201]
We need the feature, which by the way its amazing...but we dont need the default styling which we cant get rid of.

**Comment by jfschwarz** [comment]
Since, we try to keep default styling to the minimum required for making the component functional, it would be interesting to know which of the default styling rules you would like to override in particular.

That being said, you can override all default styling rules by setting inline styles (see https://github.com/effektif/react-mentions/blob/master/gh-pages/views/examples/defaultStyle.js for an example of the nested style object you can pass to `MentionsInput`) or by setting a `className` prop and overriding the default inline styles with `!important` from your css.
