### ISSUE TITLE
Add ability to disable mention lookup

### ISSUE THREAD

**Issue by adamweeks** [effektif/react-mentions#204]
We would like the ability to disable triggering mentions. Right now, our workaround is to pass an impossible regex (`/(?=a)b/`) as the `trigger` prop. A prop of `isDisabled` would be great. 

If this seems like a feature that would benefit the project, I or someone on my team would happily contribute.

**Comment by frontendphil** [comment]
If you don't want to enable a mention, then simply do not render it ;) 

```es6
<MentionsInput>
  { yourCondition && <Mention /> }
</MentionsInput>
```

**Comment by adamweeks** [comment]
@frontendphil haha, how pragmatic! Thanks!

**Comment by amazingmarvin** [comment]
@frontendphil: it's a good solution and I've been using this in production for a long time.  But I discovered that if you remove a mention which is already being used, then it causes a crash.

Sounds odd but here's my use case:

* Use enables a feature, such as labels
* User creates a new automation with a label and `"@[Example](label:nin2ri1n)"` (using `markup="@[__display__](__type__:__id__)"`) is saved to database
* User disables the labels feature
* User opens this automation

This results in a crash since `react-mentions` is looking for a `Mention` with type `label`.  Maybe this is a weird use case since not that many apps have features you can turn on and off.  But for me `isEnabled` or `isDisabled` would be great!  Ideally it would still show the mention so the user could delete it, but it wouldn't crash and wouldn't be auto-completable.

**Comment by frontendphil** [comment]
@amazingmarvin that's true. If there are mentions in the `value` which can't find a corresponding `Mention` component then the whole thing blows up. So far so good in my understanding because we would silently swallow errors otherwise. 

What would you expect from an `isDisabled` prop on a `Mention`?

**Comment by frontendphil** [comment]
Sorry. I've only now read the last sentence properly. That might be a neat addition. @jfschwarz do you have any concerns?

**Comment by jfschwarz** [comment]
I believe that if you pass an empty array for the `data` prop of the `<Mention />` element the user won't see any suggestions ever. Did you try that, @amazingmarvin?

**Comment by amazingmarvin** [comment]
@jfschwarz, @frontendphil: passing an empty array works great!  It's now behaving exactly as I'd hoped.  Thank you so much :)

**Comment by jsheffers** [comment]
The only downside to this is that you have to re-populate the mentions after you've passed in an empty array to toggle it back on.  Doing this multiple times doesn't seem to be the best solution.  

In our case we only want the mentions to happen at the beginning of a message, and then if they start typing something other than our trigger, we want to disable mentions.  In order to do this based on this issue, we'd have to send an empty array to the data prop, but if they hit backspace (let's say they entered one character that wasn't our trigger) we'd want to re-populate the data prop.  If this were an easy toggle switch we could just toggle the mention functionality and maintain the data in our data prop.  Thoughts?
