### ISSUE TITLE
renderSuggestion does nothing

### ISSUE THREAD

**Issue by godd9170** [effektif/react-mentions#22]
I can see here https://github.com/effektif/react-mentions/blob/master/src/Mention.jsx#L36 that the renderSuggestion prop is passed in, it just doesn't appear to be used for anything. Is there something I'm missing, or does the documentation need to be updated?

**Comment by jfschwarz** [comment]
The `renderSuggestion ` prop is at least briefly mentioned in the README (see last table row in the Configuration section).

If you look into the code it might first seem that the prop is not used, but it is. Take a look at https://github.com/effektif/react-mentions/blob/master/src/SuggestionsOverlay.jsx#L82 

(The `<Mention>` components work in a way that is not canonical React. Actually the props of all `<Mention>` children are accessed from the outside (React anti-pattern!) `<MentionsInput>` and `<SuggestionOverlay>` components. However, I found the API to be nicer when specifying multiple types of mentions in child components rather than as direct props of the MentionsInput.)

**Comment by godd9170** [comment]
is the same true then for onAdd? In the example you use it (https://github.com/effektif/react-mentions/blob/master/gh-pages/views/examples/MultipleTriggerView.jsx#L43) however the `console.log("added a new mention", arguments);` doesn't ever get fired. I got so much hope when I saw the comment block in the Mention component, but unlike renderSuggestion I can't get it to fire. (https://github.com/effektif/react-mentions/blob/master/src/Mention.jsx#L17)
