### ISSUE TITLE
Fix backspace behavior in IE

### ISSUE THREAD

**Issue by jfschwarz** [effektif/react-mentions#3]
IE 9-11 all show wrong behavior when the backspace key is hit. The cursor jumps to the very start of the text.

Latest versions of Chrome, Safari, and Firefox seem to work flawless.

(Example page can be opened using this URL: https://rawgit.com/effektif/react-mentions/master/examples/index.html)

**Comment by fbatista** [comment]
This is kind of a big deal bug in IE as it turns the component unusable. Isn't there a way to workaround it without having to wait for a React.js update?

Also, patching the demo page's React.js version is not a pretty move :disappointed: since people will go  there and be mislead thinking that the component works in IE 11 when in reality it doesn't.

**Comment by jfschwarz** [comment]
@fbatista, you made a good point. I'm sorry for the confusion about the demo page's React version. That's quite misleading indeed. Just updated the demo page to use original React.

Also, thanks for promoting the React `selectionchange` issue. Let's hope they will fix it soon.

**Comment by jfschwarz** [comment]
Closing this as a fix was merge into React master today
